# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('problem', models.CharField(choices=[('no_racks', 'no_racks'), ('too_few', 'too_few'), ('stupid', 'stupid')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='racks')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vote', models.IntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('solution_photo', models.ImageField(blank=True, upload_to='racks_solutions')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
