# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='problem',
            field=models.CharField(choices=[(1, 'There are no racks'), (2, 'There are too few racks'), (3, 'The racks are not safe')], max_length=16),
        ),
    ]
